# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AONYe9gZxdJ9jToiwdTrVpUh6LrIKmPy
"""

__all__=['pythagoras','circle']