# -*- coding: utf-8 -*-
"""tester

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AONYe9gZxdJ9jToiwdTrVpUh6LrIKmPy
"""

import geo.utils as utils

a,b=3,4
c= utils.pythagoras(a,b)
print('c=',c)

r=10
area = utils.circle(r)
print('area=', area)